
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "nemo"
local menu        = "wofi --show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--  hl.exec_cmd("waybar & hyprpaper & mako")
  hl.exec_cmd("dms run")
  hl.exec_cmd("fcitx5 -d")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "48")        -- physical px now that xwayland:force_zero_scaling is on (was 24 @ scale 2)
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GDK_SCALE", "2")            -- scale XWayland GTK apps; safe for Wayland-native GTK


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "scrolling",  -- niri-like scrollable tiling (see scrolling{} below)
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        -- niri-like scrollable tiling: windows live on an infinitely growing tape.
        -- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
        fullscreen_on_one_column = true,   -- a lone column fills the whole screen
        column_width             = 0.5,    -- default column width, [0.1 - 1.0]
        focus_fit_method         = 0,      -- 0 = center focused column (niri default), 1 = fit
        follow_focus             = true,   -- scroll the focused column into view
        follow_min_visible       = 0.4,    -- min fraction visible before auto-scroll kicks in
        explicit_column_widths   = "0.333, 0.5, 0.667, 1.0",  -- colresize +conf cycle
        direction                = "right", -- direction new windows appear / the strip scrolls
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

-- XWayland HiDPI: render XWayland apps at native resolution and let each toolkit
-- scale itself, so apps like WPS aren't blurry/pixelated on this 2x panel.
-- (WPS additionally gets QT_SCALE_FACTOR=2 via its .desktop override.)
-- See https://wiki.hypr.land/Configuring/XWayland/
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------
-- Hyprland 0.55.0+ uses a lua dispatcher API under hl.dsp, organized into
-- namespaces. Verified by introspecting the live hl.dsp table:
--   Top-level hl.dsp.*:  dpms, exec_cmd, exec_raw, exit, focus, force_idle,
--     force_renderer_reload, global, layout, no_op, pass, send_key_state,
--     send_shortcut, submap
--   hl.dsp.window.*:     alter_zorder, bring_to_top, center, clear_tags,
--     close, cycle_next, deny_from_group, drag, float, fullscreen,
--     fullscreen_state, kill, move, pin, pseudo, resize, set_prop, signal,
--     swap, tag, toggle_swallow
--   hl.dsp.workspace.*:  move, rename, swap_monitors, toggle_special
--   hl.dsp.group.*:      active, lock, lock_active, move_window, next, prev, toggle
--   hl.dsp.cursor.*:     move, move_to_corner
-- Arg formats (from binary error strings):
--   hl.dsp.focus{direction|monitor|window|urgent_or_last|last|workspace}
--   hl.dsp.window.move{direction | x,y(,relative) | workspace | into_group | out_of_group}
--   hl.dsp.window.resize{x, y, relative?}
--   hl.dsp.window.fullscreen{mode="fullscreen"/"maximized", action="toggle"/"set"/"unset"}
--   hl.dsp.dpms("on"/"off"/"toggle")
--   hl.dsp.layout("preselect l" / "togglesplit" / ... ) — dwindle layoutmsg
-- NOTE: `hyprctl dispatch <name> <arg>` is broken in this build (the CLI
-- parses args as lua), so every bind uses hl.dsp.* methods directly.
-- There is no monitor arg on window.move, so "move window to monitor" is
-- omitted (no clean lua equivalent in this build).
-- Keys retained from the original lua: SUPER+R (terminal), SUPER+D (menu),
-- SUPER+Q (close), SUPER+M (power menu).
-- All other keys migrated from ~/.config/hypr/dms/binds.conf.

local mainMod = "SUPER" -- Sets "Windows" key as main modifier


-- ==================
-- Application Launchers
-- ==================
hl.bind(mainMod .. " + escape",hl.dsp.exec_cmd("wlogout"))
hl.bind(mainMod .. " + R",     hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + D",     hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + T",     hl.dsp.exec_cmd(terminal)) -- parity with dms scheme
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M",     hl.dsp.exit())
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
-- Super alone (press and release) opens the dms app launcher / start menu.
-- Binds the Super key's keysym (super_l) as a release bind, so it fires on
-- key-up. See the chord caveat in chat: a release bind may also fire after
-- Super+key combos in some Hyprland versions — test Super+T release.
hl.bind(mainMod .. " + super_l", hl.dsp.exec_cmd("dms ipc call launcher toggle"), { release = true })
hl.bind(mainMod .. " + V",     hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))
hl.bind(mainMod .. " + N",     hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind("SUPER + SHIFT + N",   hl.dsp.exec_cmd("dms ipc call notepad toggle"))
hl.bind(mainMod .. " + Y",     hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"))
hl.bind(mainMod .. " + TAB",   hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))
hl.bind(mainMod .. " + X",     hl.dsp.exec_cmd("dms ipc call powermenu toggle"))

-- ==================
-- Cheat sheet
-- ==================
hl.bind("SUPER + SHIFT + slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))

-- ==================
-- Security
-- ==================
hl.bind("SUPER + ALT + L",    hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind("SUPER + SHIFT + E",  hl.dsp.exit())
hl.bind("CTRL + ALT + Delete",hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))

-- ==================
-- Audio / Brightness / Media (delegated to dms IPC)
-- ==================
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("dms ipc call audio increment 3"),   { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("dms ipc call audio decrement 3"),   { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("dms ipc call audio mute"),         { locked = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("dms ipc call audio micmute"),      { locked = true })
hl.bind("XF86AudioPause",        hl.dsp.exec_cmd("dms ipc call mpris playPause"),    { locked = true })
hl.bind("XF86AudioPlay",         hl.dsp.exec_cmd("dms ipc call mpris playPause"),    { locked = true })
hl.bind("XF86AudioPrev",         hl.dsp.exec_cmd("dms ipc call mpris previous"),     { locked = true })
hl.bind("XF86AudioNext",         hl.dsp.exec_cmd("dms ipc call mpris next"),         { locked = true })
hl.bind("CTRL + XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call mpris increment 3"), { locked = true, repeating = true })
hl.bind("CTRL + XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call mpris decrement 3"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })

-- ==================
-- Window Management
-- ==================
hl.bind(mainMod .. " + F",    hl.dsp.window.fullscreen({ mode = "fullscreen", action = "set" }))
hl.bind("SUPER + SHIFT + F",  hl.dsp.window.fullscreen({ mode = "fullscreen", action = "unset" }))
hl.bind("SUPER + SHIFT + T",  hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + W",    hl.dsp.group.toggle())     -- dms binds.conf maps SUPER,W -> togglegroup
hl.bind("SUPER + SHIFT + W",  hl.dsp.exec_cmd("dms ipc call window-rules toggle"))

-- ==================
-- Focus Navigation
-- ==================
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + H",     hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + J",     hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K",     hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + L",     hl.dsp.focus({ direction = "right" }))

-- ==================
-- Window Movement (directional)
-- ==================
hl.bind("SUPER + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + H",     hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + J",     hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + SHIFT + K",     hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + L",     hl.dsp.window.move({ direction = "right" }))

-- ==================
-- Monitor Navigation
-- ==================
hl.bind("SUPER + CTRL + left",   hl.dsp.focus({ monitor = "l" }))
hl.bind("SUPER + CTRL + right",  hl.dsp.focus({ monitor = "r" }))
hl.bind("SUPER + CTRL + H",      hl.dsp.focus({ monitor = "l" }))
hl.bind("SUPER + CTRL + J",      hl.dsp.focus({ monitor = "d" }))
hl.bind("SUPER + CTRL + K",      hl.dsp.focus({ monitor = "u" }))
hl.bind("SUPER + CTRL + L",      hl.dsp.focus({ monitor = "r" }))
-- NOTE: "move window to monitor" (SUPER+SHIFT+CTRL+dir) is omitted —
-- hl.dsp.window.move has no monitor argument in this build (only direction,
-- x+y, workspace, into_group, out_of_group). Use SUPER+SHIFT+number to move
-- a window across workspaces instead.

-- ==================
-- Workspace Navigation
-- ==================
hl.bind(mainMod .. " + Page_Down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + Page_Up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + U",         hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + I",         hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + down",    hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + up",      hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + U",       hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + I",       hl.dsp.window.move({ workspace = "e-1" }))

-- Move active window to relative workspace
hl.bind("SUPER + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + Page_Up",   hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + U",         hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + I",         hl.dsp.window.move({ workspace = "e-1" }))

-- Workspace rename
hl.bind("CTRL + SHIFT + R", hl.dsp.exec_cmd("dms ipc call workspace-rename open"))

-- ==================
-- Mouse Wheel Navigation
-- ==================
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + mouse_up",   hl.dsp.window.move({ workspace = "e-1" }))

-- ==================
-- Numbered Workspaces
-- ==================
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. key,      hl.dsp.window.move({ workspace = i }))
end

-- ==================
-- Special Workspace (Scratchpad)
-- ==================
-- SUPER+S toggles the hidden "magic" scratchpad workspace.
-- SUPER+SHIFT+S sends the active window to the scratchpad.
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + SHIFT + S",       hl.dsp.window.move({ workspace = "special:magic" }))

-- ==================
-- Scrolling layout — column operations (niri-like)
-- ==================
-- Repurposed from dwindle `preselect` (a no-op under scrolling) → swap the
-- focused column with its left/right neighbor. To restore preselect under
-- dwindle/master, change these back to "preselect l" / "preselect r".
hl.bind(mainMod .. " + bracketleft",  hl.dsp.layout("swapcol l"))
hl.bind(mainMod .. " + bracketright", hl.dsp.layout("swapcol r"))

-- Scroll the strip left/right by one whole column. (SUPER+H/L already moves
-- focus and auto-scrolls via follow_focus; these move the view independently.)
hl.bind(mainMod .. " + slash",   hl.dsp.layout("move -col"))
hl.bind(mainMod .. " + period",  hl.dsp.layout("move +col"))

-- Move the focused window into its own new column — the core niri action.
hl.bind(mainMod .. " + return",  hl.dsp.layout("promote"))

-- Column width: shrink / grow / cycle preset widths.
hl.bind("SUPER + CTRL + minus", hl.dsp.layout("colresize -0.1"))
hl.bind("SUPER + CTRL + equal", hl.dsp.layout("colresize +0.1"))
hl.bind("SUPER + CTRL + R",     hl.dsp.layout("colresize +conf"))

-- Move/resize windows with mainMod + LMB/RMB
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Manual sizing (hl.dsp.window.resize takes { x, y, relative? })
hl.bind(mainMod .. " + minus",    hl.dsp.window.resize({ x = -100, y = 0, relative = true }))
hl.bind(mainMod .. " + equal",    hl.dsp.window.resize({ x = 100,  y = 0, relative = true }))
hl.bind("SUPER + SHIFT + minus", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))
hl.bind("SUPER + SHIFT + equal", hl.dsp.window.resize({ x = 0, y = 100,  relative = true }))

-- ==================
-- Screenshots
-- ==================
hl.bind("Print",        hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + Print",  hl.dsp.exec_cmd("dms screenshot window"))

-- ==================
-- System Controls
-- ==================
hl.bind("SUPER + SHIFT + P", hl.dsp.dpms("toggle"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

